### ISSUE TITLE
Fix Typos 

### ISSUE THREAD

**Issue by Cima9642** [Cima9642/Developer-Training#3]
Fix typos in README and leave your username in contributors

**Comment by Rishav1707** [comment]
What to fix in typos? @Cima9642

**Comment by Cima9642** [comment]
> What to fix in typos? @Cima9642

the README.md file in this repo has multiple typos that need to be fixed i.e: "Hellow strange! " should be "Hello Stranger! ", etc. Feel free to fork this repo, make the changes and submit a pull request as well as leave your name behind in the contributors file if you'd like just follow proper syntax like my example. Happy Coding!
